"""Format output files with safety banners and summaries."""

from __future__ import annotations

from sql_sp_harness.transform import TransformStats


def debug_banner(parse_errors: list[str], stats: TransformStats) -> str:
    lines = [
        "-- ============================================================================",
        "-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION",
        "-- Transformed & Generated by sql-sp-harness (Python package).",
        "-- DML replaced with SELECT previews; EXEC calls replaced with PRINT stubs; variable traces injected.",
        "-- Please ensure to review the procedure for any potential side effects before running.",
        "-- ============================================================================",
        f"-- DML statements stubbed: {stats.dml_stubbed}",
        f"-- EXEC statements stubbed: {stats.exec_stubbed}",
        f"-- Trace lines added: {stats.traces_added}",
    ]
    if parse_errors:
        lines.append("-- PARSE WARNINGS (review manually):")
        for err in parse_errors:
            lines.append(f"-- {err}")
    for w in stats.warnings:
        lines.append(f"-- {w}")
    lines.append("-- ============================================================================")
    lines.append("")
    return "\n".join(lines) + "\n"
