-- ============================================================================
-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION
-- Transformed & Generated by sql-sp-harness (Python package).
-- DML replaced with SELECT previews; variable traces injected.
-- Please ensure to review the procedure for any potential side effects before running.
-- ============================================================================
-- DML statements stubbed: 4
-- Trace lines added: 0
-- ============================================================================

-- [DBG] Harness: was CREATE PROCEDURE [dbo].[usp_ComplexProcedureName]; set parameter values below.
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
if isnull(field1, '') = '' or isnull(field2, '') not in ('A','B','C')
begin
	raiserror('bjhcbkjdbckhdfbkcjfd') with seterror
	return @@error
end
if isnull(@fiend, '') <> '' and isnull(@fld2, '') not in ('A','B')
begin
	if exists(
        select 'true'
        from table1 a
        inner join table2 b
        on a.id = b.id
        where a.fld1 = @fld1
        and b.fld2 = @fld2
    )
	begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
if isnull(@fiend, '') <> '' and isnull(@fld2, '') not in ('A','B')
begin
	if exists(
		select 'true'
		from table1 a
		inner join table2 b
		on a.id = b.id
		where a.fld1 = @fld1
		and b.fld2 = @fld2
	)
	begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
if isnull(@fld2, '') not in ('A','B')
begin
	declare @flda1 int
    declare @flda2 int
    select @flda1 = fld1, @flda2 = fld2 from dbo.proc_name1 (fld1, fld2, fld3, 'a') where id = @fld1
	if @flda1 > 0
    begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
-- [DBG-PREVIEW] Would have executed:
SELECT N'INSERT to table table1' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
-- [DBG-PREVIEW] Would have executed:
SELECT N'INSERT to table table2' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
-- [DBG-PREVIEW] Would have executed:
SELECT N'INSERT to table table3' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
declare @fldx2 int
select @fldx2 = fld2 from table3 where id = @fldx1
if @fldx2 > 0
begin
	-- [DBG-PREVIEW] Would have executed:
	SELECT N'INSERT to table table4' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
end
error_label:
    raiserror('jshdcbjsdhc') with seterror
    return @@error