-- ============================================================================
-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION
-- Transformed & Generated by sql-sp-harness (Python package).
-- DML replaced with SELECT previews; EXEC calls replaced with PRINT stubs; variable traces injected.
-- Please ensure to review the procedure for any potential side effects before running.
-- ============================================================================
-- DML statements stubbed: 4
-- EXEC statements stubbed: 1
-- Trace lines added: 1
-- ============================================================================

-- [DBG] Harness: was CREATE PROCEDURE [dbo].[usp_ComplexProcedureName]; set parameter values below.
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
DECLARE @field1 int = NULL;  -- TODO: set test value
if isnull(field1, '') = '' or isnull(field2, '') not in ('A','B','C')
begin
	raiserror('bjhcbkjdbckhdfbkcjfd') with seterror
	return @@error
end
if isnull(@fiend, '') <> '' and isnull(@fld2, '') not in ('A','B')
begin
	if exists(
        select 'true'
        from table1 a
        inner join table2 b
        on a.id = b.id
        where a.fld1 = @fld1
        and b.fld2 = @fld2
    )
	begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
if isnull(@fiend, '') <> '' and isnull(@fld2, '') not in ('A','B')
begin
	if exists(
		select 'true'
		from table1 a
		inner join table2 b
		on a.id = b.id
		where a.fld1 = @fld1
		and b.fld2 = @fld2
	)
	begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
if isnull(@fld2, '') not in ('A','B')
begin
	declare @flda1 int
    declare @flda2 int
    select @flda1 = fld1, @flda2 = fld2 from dbo.proc_name1 (fld1, fld2, fld3, 'a') where id = @fld1
	if @flda1 > 0
    begin
		raiserror('jshdcbjsdhc') with seterror
		return @@error
	end
end
-- [DBG-PREVIEW] Would have executed:
SELECT N'INSERT to table table1' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
if @@rowcount = 0 and @@error <> 0
    goto error_label
-- [DBG-PREVIEW] Would have executed:
SELECT N'INSERT to table table2' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
if @@rowcount = 0 and @@error <> 0
    goto error_label
-- [DBG-EXEC] Would have executed stored procedure dbo.proc_name2
PRINT N'[DBG-EXEC] Procedure: dbo.proc_name2';
PRINT N'[DBG-EXEC] Command: EXEC dbo.proc_name2 @fld1 = @fld1, @fld2 = @fld2, @fld3 = @fld3, @fld4 = @fld4, @fld5 = @fld5, @fld6 = @fld6, @fld7 = @fld7';
PRINT N'[DBG-EXEC] Parameters:';
PRINT CONCAT(N'[DBG-EXEC] @fld1 = ', CAST(@fld1 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld2 = ', CAST(@fld2 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld3 = ', CAST(@fld3 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld4 = ', CAST(@fld4 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld5 = ', CAST(@fld5 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld6 = ', CAST(@fld6 AS NVARCHAR(4000)));
PRINT CONCAT(N'[DBG-EXEC] @fld7 = ', CAST(@fld7 AS NVARCHAR(4000)));
SELECT N'INSERT to table table3' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
set @fldx1 = scope_identity()
    PRINT CONCAT(N'[DBG] @fldx1 = ', CAST(@fldx1 AS NVARCHAR(4000)));
declare @fldx2 int
select @fldx2 = fld2 from table3 where id = @fldx1
if @fldx2 > 0
begin
	-- [DBG-PREVIEW] Would have executed:
	SELECT N'INSERT to table table4' AS [DBG_Action], @fld1 AS [@fld1], @fld2 AS [@fld2];
    if @@rowcount = 0 and @@error <> 0
        goto error_label
end
error_label:
    raiserror('jshdcbjsdhc') with seterror
    return @@error