-- ============================================================================
-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION
-- Transformed & Generated by sql-sp-harness (Python package).
-- DML replaced with SELECT previews; variable traces injected.
-- Please ensure to review the procedure for any potential side effects before running.
-- ============================================================================
-- DML statements stubbed: 14
-- Trace lines added: 36
-- ============================================================================

USE [master]
DECLARE @SQLDataFolder nvarchar(max) = cast(SERVERPROPERTY('InstanceDefaultDataPath') as nvarchar(max))
DECLARE @SQLLogFolder nvarchar(max) = cast(SERVERPROPERTY('InstanceDefaultLogPath') as nvarchar(max))
DECLARE @SQL nvarchar(max) = N'';
SET @SQL = N'
    PRINT CONCAT(N'[DBG] @SQL = ', CAST(@SQL AS NVARCHAR(4000)));
CREATE DATABASE [ASPState]
 CONTAINMENT = NONE
 ON  PRIMARY
	(NAME = N''ASPState'', FILENAME = N''' + @SQLDataFolder + 'ASPState.mdf'' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
 FILEGROUP [ASPState_mod] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
	(NAME = N''ASPState_mod'', FILENAME = N''' + @SQLLogFolder + 'ASPState_mod'' , MAXSIZE = UNLIMITED)
 LOG ON
	(NAME = N''ASPState_log'', FILENAME = N''' + @SQLLogFolder + 'ASPState_log.ldf'' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB );
ALTER DATABASE [ASPState] SET COMPATIBILITY_LEVEL = 130; ALTER DATABASE [ASPState] SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT=ON;'
EXECUTE (@SQL)
USE [AspState]
CREATE ROLE [ASPStateExecute];
CREATE ROLE [ASPStateResetRole];
CREATE ROLE [ASPStateRole];
CREATE TYPE [dbo].[tAppName] FROM [varchar](280) NOT NULL;
CREATE TYPE [dbo].[tSessionId] FROM [nvarchar](88) NOT NULL;
CREATE TYPE [dbo].[tSessionItemLong] FROM [image] NULL;
CREATE TYPE [dbo].[tSessionItemShort] FROM [varbinary](7000) NULL;
CREATE TYPE [dbo].[tTextPtr] FROM [varbinary](max) NULL;
CREATE TABLE [dbo].[ASPStateTempSessions]
(
	[SessionId] [nvarchar](88) COLLATE Latin1_General_100_BIN2 NOT NULL,
	[Created] [datetime] NOT NULL DEFAULT (getutcdate()),
	[Expires] [datetime] NOT NULL,
	[LockDate] [datetime] NOT NULL,
	[LockDateLocal] [datetime] NOT NULL,
	[LockCookie] [int] NOT NULL,
	[Timeout] [int] NOT NULL,
	[Locked] [bit] NOT NULL,
	[SessionItemShort] [varbinary](7000) NULL,
	[SessionItemLong] [varbinary](max) NULL,
	[Flags] [int] NOT NULL DEFAULT ((0)),
INDEX [Index_Expires] NONCLUSTERED
(
	[Expires] ASC
),
PRIMARY KEY NONCLUSTERED HASH
(
	[SessionId]
)WITH ( BUCKET_COUNT = 33554432)
)WITH ( MEMORY_OPTIMIZED = ON , DURABILITY = SCHEMA_ONLY )
CREATE TABLE [dbo].[ASPStateTempApplications](
	[AppId] [int] NOT NULL,
	[AppName] [char](280) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[AppId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItemExclusive3]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockAge int OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
DECLARE @actionFlags int OUTPUT WITH NATIVE_COMPILATION = NULL;  -- TODO: set test value
DECLARE @lockAge = DATEDIFF(second, LockDate, @now) = NULL;  -- TODO: set test value
DECLARE @lockCookie = LockCookie = NULL;  -- TODO: set test value
DECLARE @itemShort = NULL = NULL;  -- TODO: set test value
DECLARE @length = NULL = NULL;  -- TODO: set test value
DECLARE @locked = 1 WHERE SessionId = @id END ELSE BEGIN UPDATE dbo.ASPStateTempSessions SET Expires = DATEADD(n, Timeout, @now);
DECLARE @lockAge = 0 = NULL;  -- TODO: set test value
DECLARE @lockCookie = LockCookie = LockCookie + 1;
DECLARE @itemShort = SessionItemShort = NULL;  -- TODO: set test value
DECLARE @textptr = SessionItemLong = NULL;  -- TODO: set test value
DECLARE @length = 1 = NULL;  -- TODO: set test value
DECLARE @locked = 0 = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) = NULL;  -- TODO: set test value
DECLARE @timeout int WITH NATIVE_COMPILATION = NULL;  -- TODO: set test value
DECLARE @itemLong varbinary(max) = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
DECLARE @lockCookie int WITH NATIVE_COMPILATION = NULL;  -- TODO: set test value
DECLARE @itemLong varbinary(max) = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
DECLARE @lockCookie int WITH NATIVE_COMPILATION = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
DECLARE @lockCookie int WITH NATIVE_COMPILATION = NULL;  -- TODO: set test value
    CREATE TABLE ASPStateTempSessions (
        SessionId           nvarchar(88)    COLLATE Latin1_General_100_BIN2 NOT NULL,
        Created             datetime        NOT NULL DEFAULT GETUTCDATE(),
        Expires             datetime        NOT NULL,
        LockDate            datetime        NOT NULL,
        LockDateLocal       datetime        NOT NULL,
        LockCookie          int             NOT NULL,
        Timeout             int             NOT NULL,
        Locked              bit             NOT NULL,
        SessionItemShort    VARBINARY(7000) NULL,
        SessionItemLong     VARBINARY(max)  NULL,
        Flags               int             NOT NULL DEFAULT 0,
		PRIMARY KEY NONCLUSTERED HASH
		(
			[SessionId]
		)WITH ( BUCKET_COUNT = 33554432),
		INDEX Index_Expires (Expires)
	)WITH ( MEMORY_OPTIMIZED = ON , DURABILITY = SCHEMA_ONLY )
    CREATE TABLE dbo.ASPStateTempApplications (
        AppId               int             NOT NULL PRIMARY KEY,
        AppName             char(280)       NOT NULL,
    )
    CREATE NONCLUSTERED INDEX Index_AppName ON ASPStateTempApplications(AppName)
RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[DeleteExpiredSessions]; set parameter values below.
-- (no parameters)
    SET NOCOUNT ON
    SET DEADLOCK_PRIORITY LOW
    DECLARE @now datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    CREATE TABLE #tblExpiredSessions
    (
        SessionId nvarchar(88) NOT NULL PRIMARY KEY
    )
    /* [DBG-DISABLED] INSERT table
    --     INSERT #tblExpiredSessions (SessionId)
    --         SELECT SessionId
    --         FROM ASPStateTempSessions WITH (SNAPSHOT)
    --         WHERE Expires < @now
    */
    RAISERROR(N'[DBG] Skipped INSERT table', 0, 1) WITH NOWAIT;
    IF @@ROWCOUNT <> 0
    BEGIN
        DECLARE ExpiredSessionCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY
        FOR SELECT SessionId FROM #tblExpiredSessions
        DECLARE @SessionId nvarchar(88)
        OPEN ExpiredSessionCursor
        FETCH NEXT FROM ExpiredSessionCursor INTO @SessionId
        WHILE @@FETCH_STATUS = 0
            BEGIN
                -- [DBG-PREVIEW] Would have executed:
                SELECT N'DELETE from table ASPStateTempSessions' AS [DBG_Action], *
                FROM ASPStateTempSessions
                WHERE SessionId = @SessionId AND Expires < @now FETCH NEXT FROM ExpiredSessionCursor INTO @SessionId;
            END
        CLOSE ExpiredSessionCursor
        DEALLOCATE ExpiredSessionCursor
    END
    DROP TABLE #tblExpiredSessions
RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[GetHashCode]; set parameter values below.
DECLARE @input tAppName = NULL;  -- TODO: set test value
DECLARE @hash int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @hi_16bit   int
    DECLARE @lo_16bit   int
    DECLARE @hi_t       int
    DECLARE @lo_t       int
    DECLARE @len        int
    DECLARE @i          int
    DECLARE @c          int
    DECLARE @carry      int
    SET @hi_16bit = 0
    PRINT CONCAT(N'[DBG] @hi_16bit = ', CAST(@hi_16bit AS NVARCHAR(4000)));
    SET @lo_16bit = 5381
    PRINT CONCAT(N'[DBG] @lo_16bit = ', CAST(@lo_16bit AS NVARCHAR(4000)));
    SET @len = DATALENGTH(@input)
    PRINT CONCAT(N'[DBG] @len = ', CAST(@len AS NVARCHAR(4000)));
    SET @i = 1
    PRINT CONCAT(N'[DBG] @i = ', CAST(@i AS NVARCHAR(4000)));
    WHILE (@i <= @len)
    BEGIN
        SET @c = ASCII(SUBSTRING(@input, @i, 1))
        PRINT CONCAT(N'[DBG] @c = ', CAST(@c AS NVARCHAR(4000)));
        SET @hi_t = @hi_16bit * 32
        PRINT CONCAT(N'[DBG] @hi_t = ', CAST(@hi_t AS NVARCHAR(4000)));
        SET @hi_t = @hi_t & 0xFFFF
        PRINT CONCAT(N'[DBG] @hi_t = ', CAST(@hi_t AS NVARCHAR(4000)));
        SET @lo_t = @lo_16bit * 32
        PRINT CONCAT(N'[DBG] @lo_t = ', CAST(@lo_t AS NVARCHAR(4000)));
        SET @carry = @lo_16bit & 0x1F0000
        PRINT CONCAT(N'[DBG] @carry = ', CAST(@carry AS NVARCHAR(4000)));
        SET @carry = @carry / 0x10000
        PRINT CONCAT(N'[DBG] @carry = ', CAST(@carry AS NVARCHAR(4000)));
        SET @hi_t = @hi_t + @carry
        PRINT CONCAT(N'[DBG] @hi_t = ', CAST(@hi_t AS NVARCHAR(4000)));
        SET @hi_t = @hi_t & 0xFFFF
        PRINT CONCAT(N'[DBG] @hi_t = ', CAST(@hi_t AS NVARCHAR(4000)));
        SET @lo_16bit = @lo_16bit + @lo_t
        PRINT CONCAT(N'[DBG] @lo_16bit = ', CAST(@lo_16bit AS NVARCHAR(4000)));
        SET @hi_16bit = @hi_16bit + @hi_t + (@lo_16bit / 0x10000)
        PRINT CONCAT(N'[DBG] @hi_16bit = ', CAST(@hi_16bit AS NVARCHAR(4000)));
        SET @lo_16bit = @lo_16bit ^ @c
        PRINT CONCAT(N'[DBG] @lo_16bit = ', CAST(@lo_16bit AS NVARCHAR(4000)));
        SET @hi_16bit = @hi_16bit & 0xFFFF
        PRINT CONCAT(N'[DBG] @hi_16bit = ', CAST(@hi_16bit AS NVARCHAR(4000)));
        SET @lo_16bit = @lo_16bit & 0xFFFF
        PRINT CONCAT(N'[DBG] @lo_16bit = ', CAST(@lo_16bit AS NVARCHAR(4000)));
        SET @i = @i + 1
        PRINT CONCAT(N'[DBG] @i = ', CAST(@i AS NVARCHAR(4000)));
    END
    IF (@hi_16bit & 0x8000 <> 0)
        SET @hi_16bit = 0xFFFF0000 | @hi_16bit
        PRINT CONCAT(N'[DBG] @hi_16bit = ', CAST(@hi_16bit AS NVARCHAR(4000)));
    SET @hi_16bit = @hi_16bit * 0x10000
    PRINT CONCAT(N'[DBG] @hi_16bit = ', CAST(@hi_16bit AS NVARCHAR(4000)));
    SET @hash = @hi_16bit | @lo_16bit
    PRINT CONCAT(N'[DBG] @hash = ', CAST(@hash AS NVARCHAR(4000)));
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[GetMajorVersion]; set parameter values below.
-- (no parameters)
BEGIN
    DECLARE @version        nchar(100)
    DECLARE @dot            int
    DECLARE @hyphen         int
    DECLARE @SqlToExec      nchar(4000)
    SELECT @@ver = 7
    SELECT @version = @@Version
    SELECT @hyphen  = CHARINDEX(N' - ', @version)
    IF (NOT(@hyphen IS NULL) AND @hyphen > 0)
    BEGIN
            SELECT @hyphen = @hyphen + 3
            SELECT @dot    = CHARINDEX(N'.', @version, @hyphen)
            IF (NOT(@dot IS NULL) AND @dot > @hyphen)
            BEGIN
                    SELECT @version = SUBSTRING(@version, @hyphen, @dot - @hyphen)
                    SELECT @@ver     = CONVERT(int, @version)
            END
    END
END
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetAppID]; set parameter values below.
DECLARE @appName VARCHAR(280) = NULL;  -- TODO: set test value
DECLARE @appId int OUTPUT = NULL;  -- TODO: set test value
	SET @appName = LOWER(@appName)
	PRINT CONCAT(N'[DBG] @appName = ', CAST(@appName AS NVARCHAR(4000)));
	SET @appId = NULL
	PRINT CONCAT(N'[DBG] @appId = ', CAST(@appId AS NVARCHAR(4000)));
	SELECT @appId = AppId
	FROM ASPStateTempApplications
	WHERE AppName = @appName
	IF @appId IS NULL BEGIN
		BEGIN TRAN
		SELECT @appId = AppId
		FROM ASPStateTempApplications WITH (TABLOCKX)
		WHERE AppName = @appName
		IF @appId IS NULL
		BEGIN
			EXEC GetHashCode @appName, @appId OUTPUT
			/* [DBG-DISABLED] INSERT table
			-- 			INSERT ASPStateTempApplications
			-- 			VALUES
			-- 			(@appId, @appName)
			*/
			RAISERROR(N'[DBG] Skipped INSERT table', 0, 1) WITH NOWAIT;
			IF @@ERROR = 2627
			BEGIN
				DECLARE @dupApp tAppName
				SELECT @dupApp = RTRIM(AppName)
				FROM ASPStateTempApplications
				WHERE AppId = @appId
				RAISERROR('SQL session state fatal error: hash-code collision between applications ''%s'' and ''%s''. Please rename the 1st application to resolve the problem.',
							18, 1, @appName, @dupApp)
			END
		END
		COMMIT
	END
RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItem]; set parameter values below.
DECLARE @id tSessionId = NULL;  -- TODO: set test value
DECLARE @itemShort tSessionItemShort OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockDate datetime OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @textptr AS tTextPtr
    DECLARE @length AS int
    DECLARE @now AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, @now) AS [calculated-Expires], Locked AS [@locked], LockDateLocal AS [@lockDate], LockCookie AS [@lockCookie], CASE @locked WHEN 0 THEN SessionItemShort ELSE NULL AS [@itemShort]
    FROM ASPStateTempSessions;
            END,
        @textptr = CASE @locked
            WHEN 0 THEN SessionItemLong
            ELSE NULL
            END,
        @length = CASE @locked
            WHEN 0 THEN DATALENGTH(SessionItemLong)
            ELSE NULL
            END
    WHERE SessionId = @id
    IF @length IS NOT NULL BEGIN
        SELECT @textptr
    END
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItem2]; set parameter values below.
DECLARE @id tSessionId = NULL;  -- TODO: set test value
DECLARE @itemShort tSessionItemShort OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockAge int OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @textptr AS tTextPtr
    DECLARE @length AS int
    DECLARE @now AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, @now) AS [calculated-Expires], Locked AS [@locked], DATEDIFF(second, LockDate, @now) AS [calculated-@lockAge], LockCookie AS [@lockCookie], CASE @locked WHEN 0 THEN SessionItemShort ELSE NULL AS [@itemShort]
    FROM ASPStateTempSessions;
            END,
        @textptr = CASE @locked
            WHEN 0 THEN SessionItemLong
            ELSE NULL
            END,
        @length = CASE @locked
            WHEN 0 THEN DATALENGTH(SessionItemLong)
            ELSE NULL
            END
    WHERE SessionId = @id
    IF @length IS NOT NULL BEGIN
        SELECT @textptr
    END
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItem3]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockAge int OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
DECLARE @actionFlags int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @textptr AS tTextPtr
    DECLARE @length AS int
    DECLARE @now AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, @now) AS [calculated-Expires], Locked AS [@locked], DATEDIFF(second, LockDate, @now) AS [calculated-@lockAge], LockCookie AS [@lockCookie], CASE @locked WHEN 0 THEN SessionItemShort ELSE NULL AS [@itemShort]
    FROM ASPStateTempSessions;
            END,
        @textptr = CASE @locked
            WHEN 0 THEN SessionItemLong
            ELSE NULL
            END,
        @length = CASE @locked
            WHEN 0 THEN DATALENGTH(SessionItemLong)
            ELSE NULL
            END,
        Flags = CASE
            WHEN (Flags & 1) <> 0 THEN (Flags & ~1)
            ELSE Flags
            END,
        @actionFlags = CASE
            WHEN (Flags & 1) <> 0 THEN 1
            ELSE 0
            END
    WHERE SessionId = @id
    IF @length IS NOT NULL BEGIN
        SELECT @textptr
    END
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItemExclusive]; set parameter values below.
DECLARE @id tSessionId = NULL;  -- TODO: set test value
DECLARE @itemShort tSessionItemShort OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockDate datetime OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @textptr AS tTextPtr
    DECLARE @length AS int
    DECLARE @now AS datetime
    DECLARE @nowLocal AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    SET @nowLocal = GETDATE()
    PRINT CONCAT(N'[DBG] @nowLocal = ', CAST(@nowLocal AS NVARCHAR(4000)));
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, @now) AS [calculated-Expires], CASE Locked WHEN 0 THEN @now ELSE LockDate AS [LockDate]
    FROM ASPStateTempSessions;
            END,
        @lockDate = LockDateLocal = CASE Locked
            WHEN 0 THEN @nowLocal
            ELSE LockDateLocal
            END,
        @lockCookie = LockCookie = CASE Locked
            WHEN 0 THEN LockCookie + 1
            ELSE LockCookie
            END,
        @itemShort = CASE Locked
            WHEN 0 THEN SessionItemShort
            ELSE NULL
            END,
        @textptr = CASE Locked
            WHEN 0 THEN SessionItemLong
            ELSE NULL
            END,
        @length = CASE Locked
            WHEN 0 THEN DATALENGTH(SessionItemLong)
            ELSE NULL
            END,
        @locked = Locked,
        Locked = 1
    WHERE SessionId = @id
    IF @length IS NOT NULL BEGIN
        SELECT @textptr
    END
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetStateItemExclusive2]; set parameter values below.
DECLARE @id tSessionId = NULL;  -- TODO: set test value
DECLARE @itemShort tSessionItemShort OUTPUT = NULL;  -- TODO: set test value
DECLARE @locked bit OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockAge int OUTPUT = NULL;  -- TODO: set test value
DECLARE @lockCookie int OUTPUT = NULL;  -- TODO: set test value
    DECLARE @textptr AS tTextPtr
    DECLARE @length AS int
    DECLARE @now AS datetime
    DECLARE @nowLocal AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    SET @nowLocal = GETDATE()
    PRINT CONCAT(N'[DBG] @nowLocal = ', CAST(@nowLocal AS NVARCHAR(4000)));
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, @now) AS [calculated-Expires], CASE Locked WHEN 0 THEN @now ELSE LockDate AS [LockDate]
    FROM ASPStateTempSessions;
            END,
        LockDateLocal = CASE Locked
            WHEN 0 THEN @nowLocal
            ELSE LockDateLocal
            END,
        @lockAge = CASE Locked
            WHEN 0 THEN 0
            ELSE DATEDIFF(second, LockDate, @now)
            END,
        @lockCookie = LockCookie = CASE Locked
            WHEN 0 THEN LockCookie + 1
            ELSE LockCookie
            END,
        @itemShort = CASE Locked
            WHEN 0 THEN SessionItemShort
            ELSE NULL
            END,
        @textptr = CASE Locked
            WHEN 0 THEN SessionItemLong
            ELSE NULL
            END,
        @length = CASE Locked
            WHEN 0 THEN DATALENGTH(SessionItemLong)
            ELSE NULL
            END,
        @locked = Locked,
        Locked = 1
    WHERE SessionId = @id
    IF @length IS NOT NULL BEGIN
        SELECT @textptr
    END
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempGetVersion]; set parameter values below.
DECLARE @ver char(10) OUTPUT = NULL;  -- TODO: set test value
    SELECT @ver = '2'
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempInsertStateItemLong]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @itemLong image = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
    DECLARE @now AS datetime
    DECLARE @nowLocal AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    SET @nowLocal = GETDATE()
    PRINT CONCAT(N'[DBG] @nowLocal = ', CAST(@nowLocal AS NVARCHAR(4000)));
    /* [DBG-DISABLED] INSERT table
    --     INSERT ASPStateTempSessions
    --         (SessionId,
    --             SessionItemLong,
    --             Timeout,
    --             Expires,
    --             Locked,
    --             LockDate,
    --             LockDateLocal,
    --             LockCookie)
    --     VALUES
    --         (@id,
    --             @itemLong,
    --             @timeout,
    --             DATEADD(n, @timeout, @now),
    --             0,
    --             @now,
    --             @nowLocal,
    --             1)
    */
    RAISERROR(N'[DBG] Skipped INSERT table', 0, 1) WITH NOWAIT;
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempInsertUninitializedItem]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
    DECLARE @now AS datetime
    DECLARE @nowLocal AS datetime
    SET @now = GETUTCDATE()
    PRINT CONCAT(N'[DBG] @now = ', CAST(@now AS NVARCHAR(4000)));
    SET @nowLocal = GETDATE()
    PRINT CONCAT(N'[DBG] @nowLocal = ', CAST(@nowLocal AS NVARCHAR(4000)));
    /* [DBG-DISABLED] INSERT table
    --     INSERT ASPStateTempSessions
    --         (SessionId,
    --         SessionItemShort,
    --         Timeout,
    --         Expires,
    --         Locked,
    --         LockDate,
    --         LockDateLocal,
    --         LockCookie,
    --         Flags)
    --     VALUES
    --         (@id,
    --         @itemShort,
    --         @timeout,
    --         DATEADD(n, @timeout, @now),
    --         0,
    --         @now,
    --         @nowLocal,
    --         1,
    --         1)
    */
    RAISERROR(N'[DBG] Skipped INSERT table', 0, 1) WITH NOWAIT;
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempReleaseStateItemExclusive]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @lockCookie int = NULL;  -- TODO: set test value
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, GETUTCDATE()) AS [calculated-Expires], 0 AS [Locked]
    FROM ASPStateTempSessions
    WHERE SessionId = @id AND LockCookie = @lockCookie;
    RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempRemoveStateItem]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @lockCookie int = NULL;  -- TODO: set test value
    /* [DBG-DISABLED] DELETE table
    --     DELETE	ASPStateTempSessions
    --     WHERE	SessionId = @id AND LockCookie = @lockCookie
    */
    RAISERROR(N'[DBG] Skipped DELETE table', 0, 1) WITH NOWAIT;
	RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempResetTimeout]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, Timeout, GETUTCDATE()) AS [calculated-Expires]
    FROM ASPStateTempSessions
    WHERE SessionId = @id;
	RETURN 0
-- [DBG] Harness: was CREATE PROCEDURE [dbo].[TempUpdateStateItemShortNullLong]; set parameter values below.
DECLARE @id nvarchar(88) = NULL;  -- TODO: set test value
DECLARE @itemShort varbinary(7000) = NULL;  -- TODO: set test value
DECLARE @timeout int = NULL;  -- TODO: set test value
DECLARE @lockCookie int = NULL;  -- TODO: set test value
    -- [DBG-PREVIEW] Would have executed:
    SELECT N'UPDATE to table ASPStateTempSessions' AS [DBG_Action], DATEADD(n, @timeout, GETUTCDATE()) AS [calculated-Expires], @itemShort AS [@itemShort], NULL AS [SessionItemLong], @timeout AS [@timeout], 0 AS [Locked]
    FROM ASPStateTempSessions
    WHERE SessionId = @id AND LockCookie = @lockCookie;
    RETURN 0