-- ============================================================================
-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION
-- Transformed & Generated by sql-sp-harness (Python package).
-- DML replaced with SELECT previews; variable traces injected.
-- Please ensure to review the procedure for any potential side effects before running.
-- ============================================================================
-- DML statements stubbed: 7
-- Trace lines added: 3
-- [ParseWarning] TRY/CATCH blocks detected; DML stubbing uses line scanning.
-- ============================================================================

-- Sample: enterprise-style procedure for harness / inventory testing
-- Exercises: GO batches, revision block comment, TRY/CATCH + transaction, IF/ELSE,
-- WHILE, table variables, JOIN UPDATE, MERGE, mixed semicolon style.

IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[usp_ComplexOrderSettlement]') AND type IN (N'P', N'PC'))
    DROP PROCEDURE [dbo].[usp_ComplexOrderSettlement];

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


/*
================================================================================
 Object:     dbo.usp_ComplexOrderSettlement
 Purpose:    Settle a batch of orders with inventory and audit side effects
--------------------------------------------------------------------------------
 Mod Date     Modified By     Description
 -----------  --------------  -------------------------------------------------
 2023-06-01   platform        Initial release
 2024-11-14   ops             TRY/CATCH + explicit transaction
 2025-02-03   ops             MERGE into SettlementLog; @DryRun branch
================================================================================
*/

CREATE PROCEDURE dbo.usp_ComplexOrderSettlement
    @BatchID INT,
    @DryRun BIT = 0
AS
BEGIN
    SET NOCOUNT ON

    DECLARE @RowCount INT = 0
    DECLARE @CurrentOrderID INT
    -- introducing status variable to track the status of the procedure
    DECLARE @Status NVARCHAR(20) = N'Pending'
    DECLARE @Queue TABLE (
        OrderID INT NOT NULL PRIMARY KEY,
        SortKey INT NOT NULL
    )

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO @Queue (OrderID, SortKey)
        SELECT OrderID, ROW_NUMBER() OVER (ORDER BY OrderID)
        FROM dbo.Orders
        WHERE BatchID = @BatchID
          AND OrderStatus = @Status

        IF @@ROWCOUNT = 0
        BEGIN
            RAISERROR(N'No orders found for batch %d', 16, 1, @BatchID)
            RETURN
        END

        WHILE EXISTS (SELECT 1 FROM @Queue)
        BEGIN
            SELECT TOP 1
                @CurrentOrderID = OrderID
            FROM @Queue
            ORDER BY SortKey

            IF @DryRun = 1
            BEGIN
                SET @RowCount = @RowCount + 1
                PRINT CONCAT(N'[DBG] @RowCount = ', CAST(@RowCount AS NVARCHAR(4000)));
            END
            ELSE
            BEGIN
                -- [DBG-PREVIEW] Would have executed:
                SELECT N'UPDATE to table dbo.Orders' AS [DBG_Action], N'Settled' AS [OrderStatus], GETDATE() AS [calculated-SettledDate]
                FROM dbo.Orders
                WHERE OrderID = @CurrentOrderID;

                -- [DBG-PREVIEW] Would have executed:
                SELECT N'UPDATE to table i' AS [DBG_Action], i.ReservedQty - oi.Quantity AS [calculated-ReservedQty]
                FROM dbo.Inventory i INNER JOIN dbo.OrderItems oi ON oi.ProductID = i.ProductID
                WHERE oi.OrderID = @CurrentOrderID /************** * Comment block * * More comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines * * Even more comment lines ***************/;

                /* [DBG-DISABLED] MERGE statement
                --                 MERGE dbo.SettlementLog AS tgt
                --                 USING (SELECT @CurrentOrderID AS OrderID) AS src
                --                 ON tgt.OrderID = src.OrderID
                --                 WHEN MATCHED THEN
                */
                RAISERROR(N'[DBG] Skipped MERGE statement', 0, 1) WITH NOWAIT;
                    -- [DBG-PREVIEW] Would have executed:
                    SELECT N'UPDATE to table ' AS [DBG_Action], GETDATE() WHEN NOT MATCHED THEN AS [calculated-UpdatedDate]
                    FROM ;
                    /* [DBG-DISABLED] INSERT table
                    --                     INSERT (OrderID, BatchID, CreatedDate)
                    --                     VALUES (src.OrderID, @BatchID, GETDATE())
                    */
                    RAISERROR(N'[DBG] Skipped INSERT table', 0, 1) WITH NOWAIT;

                -- [DBG-PREVIEW] Would have executed:
                SELECT N'INSERT to table dbo.AuditLog' AS [DBG_Action], @CurrentOrderID AS [@CurrentOrderID], N'SETTLE' AS [ActionCode], GETDATE() AS [calculated-CreatedDate];

                SET @RowCount = @RowCount + 1
                PRINT CONCAT(N'[DBG] @RowCount = ', CAST(@RowCount AS NVARCHAR(4000)));
            END

            DELETE FROM @Queue WHERE OrderID = @CurrentOrderID
        END

        COMMIT TRANSACTION
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION

        -- [DBG-PREVIEW] Would have executed:
        SELECT N'INSERT to table dbo.ErrorLog' AS [DBG_Action], @BatchID AS [@BatchID], ERROR_MESSAGE() AS [calculated-ErrorMessage], GETDATE() AS [calculated-CreatedDate];

        SET @Status = N'Failed'
        PRINT CONCAT(N'[DBG] @Status = ', CAST(@Status AS NVARCHAR(4000)));
        THROW
    END CATCH
END
