-- ============================================================================
-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION
-- Generated by sql-sp-harness. DML replaced with SELECT previews; variable traces injected.
-- ============================================================================
-- DML statements stubbed: 2
-- Trace lines added: 3
--   [ParseWarning] TRY/CATCH blocks detected; DML stubbing uses line scanning.
-- ============================================================================

-- Sample: employee bonus stored procedure (used by tests)

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[usp_ProcessEmployeeBonus]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [dbo].[usp_ProcessEmployeeBonus];

/*
================================================================================
 Object:     dbo.usp_ProcessEmployeeBonus
 Purpose:    Apply a bonus to an employee and record the change in AuditLog
--------------------------------------------------------------------------------
 Mod Date     Modified By     Description
 -----------  --------------  -------------------------------------------------
 2024-03-12   J.Smith         Initial release — bonus UPDATE + audit INSERT
 2025-01-08   A.Patel         Wrapped DML in TRY/CATCH; added @IsSuccess output
================================================================================
*/

CREATE PROCEDURE dbo.usp_ProcessEmployeeBonus
    @EmployeeID INT,
    @BonusAmount DECIMAL(18, 2)
AS
BEGIN
    SET NOCOUNT ON

    DECLARE @IsSuccess BIT = 0
    DECLARE @ErrMsg NVARCHAR(4000)

    -- Process bonus inside TRY/CATCH
    BEGIN TRY
        -- [DBG-PREVIEW] Would have executed:
        SELECT N'UPDATE to table dbo.Employees' AS [DBG_Action], Bonus + @BonusAmount AS [calculated-Bonus], GETDATE() AS [calculated-LastModified]
        FROM dbo.Employees
        WHERE EmployeeID = @EmployeeID;

        -- [DBG-PREVIEW] Would have executed:
        SELECT N'INSERT to table dbo.AuditLog' AS [DBG_Action], @EmployeeID AS [@EmployeeID], CONCAT('Bonus processed: $', @BonusAmount) AS [calculated-LogMessage], GETDATE() AS [calculated-CreatedDate];

        SET @IsSuccess = 1
        PRINT CONCAT(N'[DBG] @IsSuccess = ', CAST(@IsSuccess AS NVARCHAR(4000)));
    END TRY
    BEGIN CATCH
        SET @IsSuccess = 0
        PRINT CONCAT(N'[DBG] @IsSuccess = ', CAST(@IsSuccess AS NVARCHAR(4000)));
        SET @ErrMsg = ERROR_MESSAGE()
        PRINT CONCAT(N'[DBG] @ErrMsg = ', CAST(@ErrMsg AS NVARCHAR(4000)));
    END CATCH
END